---
# tasks file for create_fvRsCons
- include_vars:
   dir: "{{path}}/vars/vars_wip"
#Execute create_fvRsCons
- include_tasks: "{{repository_path}}/pre_query_fvRsCons.yml"
- include_tasks: "{{repository_path}}/post_query_aci_tenant.yml"
- include_tasks: "{{repository_path}}/post_query_aci_ap.yml"
- include_tasks: "{{repository_path}}/post_query_aci_epg.yml"
- include_tasks: "{{repository_path}}/create_fvRsCons.yml"
- include_tasks: "{{repository_path}}/post_query_fvRsCons.yml"
