---
# tasks file for create_l3extLIfP
- include_vars:
   dir: "{{path}}/vars/vars_wip"
#Execute create_l3extLIfP
- include_tasks: "{{repository_path}}/pre_query_l3extLIfP.yml"
- include_tasks: "{{repository_path}}/post_query_aci_l3out.yml"
- include_tasks: "{{repository_path}}/post_query_aci_tenant.yml"
- include_tasks: "{{repository_path}}/post_query_aci_switch_policy_leaf_profile.yml"
- include_tasks: "{{repository_path}}/create_l3extLIfP.yml"
- include_tasks: "{{repository_path}}/post_query_l3extLIfP.yml"
