---
# tasks file for create_snmpTrapFwdServerPv3
- include_vars:
   dir: "{{path}}/vars/vars_wip"
#Execute create_snmpTrapFwdServerPv3
- include_tasks: "{{repository_path}}/pre_query_snmpTrapFwdServerPv3.yml"
- include_tasks: "{{repository_path}}/create_snmpTrapFwdServerPv3.yml"
- include_tasks: "{{repository_path}}/post_query_snmpTrapFwdServerPv3.yml"
