---
- name: File CleanUp and Processing
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ../../vars/global.yaml


  roles:
  - pre_file_processing


- name: Create a Snapshot Before the Change  
  hosts: all
  connection: local
  gather_facts: no
  vars_files:
    - ../../vars/global.yaml

  roles:
  - create_snapshot_before_change