---
# tasks file for create_aci_bd_to_l3out
- include_vars:
   dir: "{{path}}/vars/vars_wip"
#Execute create_aci_bd_to_l3out
- include_tasks: "{{repository_path}}/post_query_aci_tenant.yml"
- include_tasks: "{{repository_path}}/post_query_aci_bd.yml"
- include_tasks: "{{repository_path}}/post_query_aci_l3out.yml"
- include_tasks: "{{repository_path}}/pre_query_aci_bd_to_l3out.yml"
- include_tasks: "{{repository_path}}/create_aci_bd_to_l3out.yml"
- include_tasks: "{{repository_path}}/post_query_aci_bd_to_l3out.yml"
