---
# tasks file for create_aci_fabric_node
- include_vars:
   dir: "{{path}}/vars/vars_wip"
#Execute create_aci_fabric_node
# - include_tasks: "{{repository_path}}/pre_query_aci_fabric_node.yml"
- include_tasks: "{{repository_path}}/create_aci_fabric_node.yml"
- include_tasks: "{{repository_path}}/post_query_aci_fabric_node.yml"
