---
# tasks file for create_vmmDomP
- include_vars:
   dir: "{{path}}/vars/vars_wip"
#Execute create_vmmDomP
# - include_tasks: "{{repository_path}}/pre_query_vmmDomP.yml"
- include_tasks: "{{repository_path}}/post_query_aci_vmm_domain.yml"
- include_tasks: "{{repository_path}}/create_vmmDomP.yml"
- include_tasks: "{{repository_path}}/post_query_vmmDomP.yml"
