---
# tasks file for create_aci_l3out
- include_vars:
   dir: "{{path}}/vars/vars_wip"
#Execute createaci_l3out
- include_tasks: "{{repository_path}}/post_query_aci_tenant.yml"
- include_tasks: "{{repository_path}}/post_query_aci_vrf.yml"
- include_tasks: "{{repository_path}}/post_query_aci_domain.yml"
- include_tasks: "{{repository_path}}/pre_query_aci_l3out.yml"
- include_tasks: "{{repository_path}}/create_aci_l3out.yml"
- include_tasks: "{{repository_path}}/post_query_aci_l3out.yml"
