---
# tasks file for create_aci_switch_policy_vpc_protection_group
- include_vars:
   dir: "{{path}}/vars/vars_wip"
#Execute create_aci_switch_policy_vpc_protection_group
- include_tasks: "{{repository_path}}/pre_query_aci_switch_policy_vpc_protection_group.yml"
- include_tasks: "{{repository_path}}/create_aci_switch_policy_vpc_protection_group.yml"
- include_tasks: "{{repository_path}}/post_query_aci_switch_policy_vpc_protection_group.yml"
