---
# tasks file for create_dhcpLbl
- include_vars:
   dir: "{{path}}/vars/vars_wip"
#Execute create_dhcpLbl
# - include_tasks: "{{repository_path}}/pre_query_dhcpLbl.yml"
- include_tasks: "{{repository_path}}/post_query_dhcpRelayP.yml"
- include_tasks: "{{repository_path}}/create_dhcpLbl.yml"
- include_tasks: "{{repository_path}}/post_query_dhcpLbl.yml"
