---

########################################################################
#Add new SNMP v3 Trap Receivers to snmp Dest Group
#Owner: Hui Yu
#Prerequisites: N/A
########################################################################

- name: File CleanUp and Processing before the Change
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ../../vars/global.yaml  


  roles:
  - pre_file_processing
  - validate_apic_id

- name: tasks related to ACI  
  hosts: all
  connection: local
  gather_facts: no
  vars_files:
    - ../../vars/global.yaml

  roles:
  - create_snapshot_before_change


  #related to the role/project
  - create_snmpTrapDestv3
  - create_snapshot_after_change

- name: File CleanUp after the Change
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ../../vars/global.yaml
  
  roles:
  - post_file_cleanup
