---
# tasks file for create_snmpTrapDestv3
- include_vars:
   dir: "{{path}}/vars/vars_wip"
#Execute create_snmpTrapDestv3
# - include_tasks: "{{repository_path}}/pre_query_snmpTrapDestv3.yml"
- include_tasks: "{{repository_path}}/create_snmpTrapDestv3.yml"
- include_tasks: "{{repository_path}}/post_query_snmpTrapDestv3.yml"
