---

########################################################################
#Bind User Tenant Domain to VLAN pool
#Owner: Hui Yu
#Prerequisites: aci_domain,aci_vlan_pool
########################################################################

- name: File CleanUp and Processing before the Change
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ../../vars/global.yaml  


  roles:
  - pre_file_processing
  - validate_apic_id

- name: tasks related to ACI  
  hosts: all
  connection: local
  gather_facts: no
  vars_files:
    - ../../vars/global.yaml

  roles:
  - create_snapshot_before_change


  #related to the role/project
  - create_aci_domain_to_vlan_pool
  - create_snapshot_after_change

- name: File CleanUp after the Change
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ../../vars/global.yaml
  
  roles:
  - post_file_cleanup
