---

########################################################################
#Add a new subnet to ExtEPG
#Owner: Hui Yu
#Prerequisites: aci_l3out,aci_tenant,aci_exepg
########################################################################

- name: File CleanUp and Processing before the Change
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ../../vars/global.yaml  


  roles:
  - pre_file_processing
  - validate_apic_id

- name: tasks related to ACI  
  hosts: all
  connection: local
  gather_facts: no
  vars_files:
    - ../../vars/global.yaml

  roles:
  - create_snapshot_before_change


  #related to the role/project
  - create_aci_l3out_extsubnet
  - create_snapshot_after_change

- name: File CleanUp after the Change
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ../../vars/global.yaml
  
  roles:
  - post_file_cleanup
